Set correct text if there is no PLR
openoereb/pyramid_oereb_mfp pull request #12
Opened 2019-06-28 12:31 UTC by marionb

**This PR:**
Adds some text in the template if there is no PLR that a plies to the printed real estate.
Fixes #11 (https://jira.camptocamp.com/browse/GSOREB-273)

**To Test:**
In the print_proxy make the function [convert_to_printable_extract](https://github.com/openoereb/pyramid_oereb/blob/00ec0fd23f278c5b4dfb4930b357ed671b3afd01/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L171) return an empty `RealEstate_RestrictionOnLandownershipin` the extract_dict list by adding the following lines at the end of the function

    extract_dict['RealEstate_RestrictionOnLandownership'] = []
    extract_dict['NotConcernedTheme'] += extract_dict['ConcernedTheme']
    extract_dict['ConcernedTheme'] = []

2019-06-28 13:13 UTC, svareg requested changes
Hello,

The french text is not very good. I would propose 
NoPLR = Il n’existe aucun thème pour cette parcelle.
or
NoPLR = Il n’existe aucun thème pour ce terrain.

I think it needs an uppercase T at themen as well in the german text.

Otherwise it looks good for me.

2019-06-28 14:21 UTC, marionb commented
@svareg Thanks for the hint. I just corrected it.

2019-06-28 14:38 UTC, svareg approved these changes

2019-06-28 14:45 UTC, merged

2019-07-01 05:57 UTC, jwkaltz reviewed
Please fix typos, thanks

2019-07-01 05:57 UTC, jwkaltz commented on print-apps/oereb/Report_de.properties
> +NoPLR = Es exisiteren keine Themen für dieses Grundstück
Es existieren

2019-07-01 05:57 UTC, jwkaltz commented on print-apps/oereb/Report_de.properties
> +NoPLR = Es exisiteren keine Themen für dieses Grundstück
Und Punkt am Ende des Satzes fehlt

2019-07-01 05:57 UTC, jwkaltz commented on print-apps/oereb/Report.properties
> +NoPLR = No concerned theme for this real estate
Punkt am Ende des Satzes fehlt

2019-07-02 04:46 UTC, marionb commented on print-apps/oereb/Report.properties
> +NoPLR = No concerned theme for this real estate
Fixed typos in #13