added SubunitOfLandRegister replacement to properties and TOC
openoereb/pyramid_oereb_mfp pull request #32
Opened 2019-10-11 07:14 UTC by voisardf

merge PRhttps://github.com/openoereb/pyramid_oereb_mfp/pull/31 first.

fixes 
- [x] issue https://github.com/openoereb/pyramid_oereb_mfp/issues/27 - subunit_of_land_register not printed on TOC-page in PDF extract

2019-10-11 12:00 UTC, voisardf commented
example pdf : 
[20191011015222_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3717405/20191011015222_extract.pdf)

2019-10-11 13:31 UTC, vvmruder approved these changes
Thanks a lot. I hope this is sustainable and the federal specification will not rely on the attachments... -.-

2019-10-14 11:58 UTC, kdeininger approved these changes

2019-10-15 10:49 UTC, marionb requested changes

2019-10-15 10:49 UTC, marionb commented on print-apps/oereb/Report_de.properties
> +Topicsaffectingtherealestate_ofthemunicipalityof_ = Eigentumsbeschränkungen, welche das Grundstück %s in %s %s betreffen
```suggestion
Topicsaffectingtherealestate_ofthemunicipalityof_ = Eigentumsbeschränkungen, welche das Grundstück %s in %s%s betreffen
```

2019-10-15 10:49 UTC, marionb commented on print-apps/oereb/pdfextract.jrxml
> -			<!--
Can you re-add this note. It should not be removed eventhough it is just a comment.

2019-10-15 15:13 UTC, voisardf commented
Addressed comments. Should be ok now

2019-10-17 07:27 UTC, marionb approved these changes
Looks good now. Thanks!

2019-10-17 07:53 UTC, voisardf commented
thanks! merging

2019-10-17 07:54 UTC, merged